<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HelpLine.FancyHelp.Tests</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <RootNamespace>HelpLine.FancyHelp.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TestResults\**" />
    <EmbeddedResource Remove="TestResults\**" />
    <None Remove="TestResults\**" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelpLine.FancyHelp\HelpLine.FancyHelp.csproj" />
  </ItemGroup>
</Project>
